//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public decimal ALUMNO_ID { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string RUT { get; set; }
        public System.DateTime FECH_NAC { get; set; }
        public decimal APODERADO_APODERADO_ID { get; set; }
        public decimal CURSO_ID_CURSO { get; set; }
        public Nullable<decimal> DEUDA { get; set; }
    
        public virtual APODERADO APODERADO { get; set; }
        public virtual CURSO CURSO { get; set; }
    }
}
