//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLEGIO
    {
        public COLEGIO()
        {
            this.CURSO = new HashSet<CURSO>();
        }
    
        public decimal COLEGIO_ID { get; set; }
        public string NOMBRE_COLEGIO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual ICollection<CURSO> CURSO { get; set; }
    }
}
