//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public CURSO()
        {
            this.ALUMNO = new HashSet<ALUMNO>();
            this.ENCARGADO = new HashSet<ENCARGADO>();
        }
    
        public decimal ID_CURSO { get; set; }
        public string NOMBRE_CURSO { get; set; }
        public decimal COLEGIO_COLEGIO_ID { get; set; }
    
        public virtual ICollection<ALUMNO> ALUMNO { get; set; }
        public virtual COLEGIO COLEGIO { get; set; }
        public virtual ICollection<ENCARGADO> ENCARGADO { get; set; }
    }
}
