//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCARGADO
    {
        public ENCARGADO()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
            this.PAGO = new HashSet<PAGO>();
        }
    
        public decimal ENCARGADO_ID { get; set; }
        public string NOMBRE { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string TELEFONO { get; set; }
        public decimal AGENTE_AGENTE_ID { get; set; }
        public string USERNAME { get; set; }
        public decimal ROLES_ROLES_ID { get; set; }
        public decimal CURSO_ID_CURSO { get; set; }
    
        public virtual AGENTE AGENTE { get; set; }
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        public virtual CURSO CURSO { get; set; }
        public virtual ROLES ROLES { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
