//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public decimal PAGO_ID { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
        public decimal MONTO_PAGO { get; set; }
        public decimal CONTRATO_CONTRATO_ID { get; set; }
        public Nullable<decimal> APODERADO_APODERADO_ID { get; set; }
        public Nullable<decimal> ENCARGADO_ENCARGADO_ID { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual APODERADO APODERADO { get; set; }
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual ENCARGADO ENCARGADO { get; set; }
    }
}
