//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public ROLES()
        {
            this.ADMINISTRADOR = new HashSet<ADMINISTRADOR>();
            this.AGENTE = new HashSet<AGENTE>();
            this.APODERADO = new HashSet<APODERADO>();
            this.ENCARGADO = new HashSet<ENCARGADO>();
        }
    
        public decimal ROLES_ID { get; set; }
        public string NOMBRE_ROL { get; set; }
    
        public virtual ICollection<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual ICollection<AGENTE> AGENTE { get; set; }
        public virtual ICollection<APODERADO> APODERADO { get; set; }
        public virtual ICollection<ENCARGADO> ENCARGADO { get; set; }
    }
}
