//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SER_ADICIONAL
    {
        public SER_ADICIONAL()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public decimal SER_ID { get; set; }
        public string NOMBRE_SER { get; set; }
        public decimal PRECIO { get; set; }
        public string TIPO { get; set; }
    
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
    }
}
