//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        public TOUR()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public decimal TOUR_ID { get; set; }
        public string NOMBRE_TOURS { get; set; }
        public decimal PRECIO_BASE { get; set; }
        public decimal DIAS { get; set; }
        public decimal PRECIO_TOTAL { get; set; }
        public decimal DESTINO_DESTINO_ID { get; set; }
    
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        public virtual DESTINO DESTINO { get; set; }
    }
}
