//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ReferenciaWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WCFPolizas")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ReferenciaWCF.Poliza))]
    public partial class BaseRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Poliza", Namespace="http://schemas.datacontract.org/2004/07/WCFPolizas")]
    [System.SerializableAttribute()]
    public partial class Poliza : WebApplication1.ReferenciaWCF.BaseRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiasCoberturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncidenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aseguradoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidadPersonasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int montoPolizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrePolizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroPolizaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiasCobertura {
            get {
                return this.DiasCoberturaField;
            }
            set {
                if ((this.DiasCoberturaField.Equals(value) != true)) {
                    this.DiasCoberturaField = value;
                    this.RaisePropertyChanged("DiasCobertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Incidencia {
            get {
                return this.IncidenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidenciaField, value) != true)) {
                    this.IncidenciaField = value;
                    this.RaisePropertyChanged("Incidencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aseguradora {
            get {
                return this.aseguradoraField;
            }
            set {
                if ((object.ReferenceEquals(this.aseguradoraField, value) != true)) {
                    this.aseguradoraField = value;
                    this.RaisePropertyChanged("aseguradora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidadPersonas {
            get {
                return this.cantidadPersonasField;
            }
            set {
                if ((this.cantidadPersonasField.Equals(value) != true)) {
                    this.cantidadPersonasField = value;
                    this.RaisePropertyChanged("cantidadPersonas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int montoPoliza {
            get {
                return this.montoPolizaField;
            }
            set {
                if ((this.montoPolizaField.Equals(value) != true)) {
                    this.montoPolizaField = value;
                    this.RaisePropertyChanged("montoPoliza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrePoliza {
            get {
                return this.nombrePolizaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrePolizaField, value) != true)) {
                    this.nombrePolizaField = value;
                    this.RaisePropertyChanged("nombrePoliza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroPoliza {
            get {
                return this.numeroPolizaField;
            }
            set {
                if ((this.numeroPolizaField.Equals(value) != true)) {
                    this.numeroPolizaField = value;
                    this.RaisePropertyChanged("numeroPoliza");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaWCF.IServicioPoliza")]
    public interface IServicioPoliza {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPoliza/ObtenerPoliza", ReplyAction="http://tempuri.org/IServicioPoliza/ObtenerPolizaResponse")]
        WebApplication1.ReferenciaWCF.Poliza ObtenerPoliza(string Identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPoliza/ObtenerPoliza", ReplyAction="http://tempuri.org/IServicioPoliza/ObtenerPolizaResponse")]
        System.Threading.Tasks.Task<WebApplication1.ReferenciaWCF.Poliza> ObtenerPolizaAsync(string Identificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPolizaChannel : WebApplication1.ReferenciaWCF.IServicioPoliza, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPolizaClient : System.ServiceModel.ClientBase<WebApplication1.ReferenciaWCF.IServicioPoliza>, WebApplication1.ReferenciaWCF.IServicioPoliza {
        
        public ServicioPolizaClient() {
        }
        
        public ServicioPolizaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPolizaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPolizaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPolizaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ReferenciaWCF.Poliza ObtenerPoliza(string Identificacion) {
            return base.Channel.ObtenerPoliza(Identificacion);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ReferenciaWCF.Poliza> ObtenerPolizaAsync(string Identificacion) {
            return base.Channel.ObtenerPolizaAsync(Identificacion);
        }
    }
}
